version: '3'
services:
    nginx:
        build:
            context: ./docker
            dockerfile: ./nginx.docker
        volumes:
            - ./:/var/www
            - ./docker/nginx/ssl:/etc/nginx/ssl
        ports:
            - "8080:80"
        links:
            - php-fpm
    php-fpm:
        build:
            context: ./docker
            dockerfile: ./php-fpm.docker
        volumes:
            - ./:/var/www
        links:
            - mysql
            - redis
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=mysql"
            - "REDIS_PORT=6379"
            - "REDIS_HOST=redis"
    php-cli:
        build:
            context: ./docker
            dockerfile: ./php-cli.docker
        volumes:
            - ./:/var/www
        links:
            - mysql
            - redis
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=mysql"
            - "REDIS_PORT=6379"
        tty: true
    mysql:
        image: mysql:5.7
        restart: always
        environment:
          - "MYSQL_ROOT_PASSWORD=secret"
          - "MYSQL_USER=app"
          - "MYSQL_PASSWORD=secret"
          - "MYSQL_DATABASE=app"
        ports:
            - 3306:3306
        volumes:
        - ./storage/docker/mysql:/var/lib/mysql
        expose:
            - 3306
    redis:
        image: redis:3.0
        ports:
            - "63791:6379"
    node:
        image: node:18.6-alpine
        volumes:
            - ./:/var/www
        working_dir: /var/www
        tty: true